FROM nvidia/cuda:12.8.0-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      python3 python3-pip python3-venv ca-certificates \
      git curl \
      poppler-utils tesseract-ocr \
      libgl1 libglib2.0-0 libsm6 libxrender1 libxext6 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/requirements.txt .

RUN python3 -m pip install --upgrade pip setuptools wheel \
 && python3 -m pip install --no-cache-dir -r requirements.txt \
      --extra-index-url https://download.pytorch.org/whl/cu128

# fastText model
RUN curl -L -o lid.176.ftz \
    https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.ftz

RUN python3 -m spacy download en_core_web_sm && \
    python3 -m spacy download de_core_news_sm

COPY backend/ .

EXPOSE 8000

CMD ["uvicorn", "backendCode:app", "--host", "0.0.0.0", "--port", "8000"]
